### ISSUE TITLE
Incorrect version of core-io in latest connector

### ISSUE THREAD

**Issue by tk6022** [couchbase/couchbase-kafka-connector#12]
The latest version of the kafka-connector (1.2.1) relies on version 1.2.3-beta of core-io which is not available in maven central. Can you please release a new version of the connector relying on the available 1.2.3 release of core-io as soon as possible?

**Comment by tk6022** [comment]
Can anyone comment on this please?

**Comment by daschl** [comment]
@tk6022 1.2.3-beta is published on the couchbase repository and transitively linked (since the kafka connector is published to maven central). isn't it not picked up?

http://search.maven.org/#artifactdetails%7Ccom.couchbase.client%7Ckafka-connector%7C1.2.1%7Cjar includes

``` xml
  <distributionManagement>
    <repository>
      <id>couchbase</id>
      <url>http://files.couchbase.com/maven2</url>
    </repository>
  </distributionManagement>
```

**Comment by daschl** [comment]
Note that 1.2.3 GA is already released and the next kafka version will pick it up. this was a compromise we had to make in order to get some important dcp fixes in the kafka connector which did not align with the regular SDK release cadence.

**Comment by patelliandrea** [comment]
Anyway, I tried both 1.2.3-beta and 1.2.3 GA and seems like the DCP flow control buffer accounting is still not working.
If I set the DCP connection buffer to 10kb, the stream just gets stuck after 500 messages...

Am I misssing something?

**Comment by daschl** [comment]
@avsej ?
