### ISSUE TITLE
Connector does not stop when reaching the end

### ISSUE THREAD

**Issue by legatoslide** [couchbase/couchbase-kafka-connector#16]
Tested on: Connector 2.0.0 + Core IO 1.2.6

Here is the client code:

connector.run(connector.startState(), connector.endState());

I get all the expected past mutations. But I was expecting the process to stop once all mutations have been pushed to Kafka (as it was the case with version < 2.0). Instead, the process stays running, however, new mutations are ignored.

Regards,
David

**Comment by avsej** [comment]
The endState() here means wait for all events infinitely

**Comment by legatoslide** [comment]
Sorry, I did not reported the right client code. Here it is:

`connector.run(connector.startState(), connector.currentState());`

**Comment by avsej** [comment]
Yes, unfortunately it is a limitation, for now we new core API, and we will address this scenario in the next release. I will try to come up with workaround and post it on forums
