### ISSUE TITLE
Loosing first message if Kafka topic does not exist

### ISSUE THREAD

**Issue by legatoslide** [couchbase/couchbase-kafka-connector#17]
Tested on Connector 2.0.0 + Core IO 1.2.6

If we start a brand new Kafka in which the topic used by the connector does not exist yet, the first message is lost:

```
WARN - Error while fetching metadata [{TopicMetadata for topic default -> 
No partition metadata for topic default due to kafka.common.LeaderNotAvailableException}] for topic [default]: class kafka.common.LeaderNotAvailableException 
ERROR - Failed to send requests for topics default with correlation ids in [0,8]
WARN - Exception while Handling DCP Events com.couchbase.kafka.DCPEvent@323701e9
kafka.common.FailedToSendMessageException: Failed to send messages after 3 tries.
```

If  Thread.sleep(2000) is added before calling connector.run() then we do not loose this first message.

Regards,
David

**Comment by avsej** [comment]
Did you configured Kafka to create topic automatically?

**Comment by legatoslide** [comment]
The topic is actually created and I get 4999 mutations while I should get 5000. It seems the creation of the topic takes some time in Kafka. More time than the 3 retries to post the 1st message. Not sure it is really a bug - it can be handled on the "client" side.

**Comment by avsej** [comment]
in connector we assume that topic exists before starting work. Would you expect it to backoff and retry in connector? the kafka client already tried that, and it is in the log record

**Comment by legatoslide** [comment]
I was simply expecting to not loose any message. If the connector assumes that the topic exists, well that's ok.
