### ISSUE TITLE
How stop Couchbase kafka connector from running

### ISSUE THREAD

**Issue by belaazim** [couchbase/couchbase-kafka-connector#20]
Hi,
We can run a CouchbaseKafkaConnector and listen/push dcp events to kafka.
How could we stop this CouchbaseKafkaConnector from running ?
Kind regards,
Maherzia

**Comment by avsej** [comment]
At the moment. it does not implement this functionality. Could you give more details about the usecase?

**Comment by belaazim** [comment]
I'm testing CouchBase Data change publishing.
In my sense, pushing dcp events to kafka could be controlled (I mean couchbase kafka connection).
1. Run
2. stop
3. Restart
