### ISSUE TITLE
Parallel reads (Load balance reads)

### ISSUE THREAD

**Issue by amukiza** [couchbase/couchbase-kafka-connector#22]
This is more of a question than an Issue but I could not find a forum through which to ask: 

Is it possible to parallelize the consumption of change events?
In other words can one load balance the reads from couchbase server across say different threads/actors or even application/microservice instances?

I am not too sure about this, but If the connector accepted a view (query), which is executed at the db level then this would potentially satisfy my use case. Is this something that is currently supported and I haven't figured it out yet?

Currently, I am considering creating actors/processes each handling the different kinds of documents but I am doing the selection using filters  which I don't think would give me the same performance as a view or query.

**Comment by legatoslide** [comment]
IMO, you should consider parallelism while consuming from Kafka: you publish your different types of documents to different partitions and then you consume in parallel from those different partitions.
