### ISSUE TITLE
Multiple topics (demux)

### ISSUE THREAD

**Issue by legatoslide** [couchbase/couchbase-kafka-connector#23]
Currently, the Kafka topic is provided at start up of the Connector and there can only be one.
Now let's assume you want to push to different topics depending on the documents, the kind of mutation (Insert / Remove) etc... in order to have specialized jobs consuming from each topic.
Currently, it is not possible, at least with a single Connector: a workaround is possible by creating 1 connector by topic with the right filter but at the cost of an increase of DCP consumers on the server.
It would be great to be able to use 1 single Connector as a demux and to have the possibility to send messages to different topics on a DCP Event basis.

**Comment by WillGardella** [comment]
Thanks for the report. I've added this to an internal requirements doc we have on server side eventing. You're right about the possible workarounds. We're considering ways to make this easier and more efficient.

**Comment by amukiza** [comment]
This is what I referred to in this [issue](https://github.com/couchbase/couchbase-kafka-connector/issues/22), which I have closed. 

Essentially being able to either map kinds of documents or events to a topic would work. I am currently running a few processes as a work around for consuming different changes at the same time using filters
