### ISSUE TITLE
ZookeeperStateSerializer will not correctly serialize state

### ISSUE THREAD

**Issue by stanley-shi** [couchbase/couchbase-kafka-connector#4]
@Override
    public void dump(BucketStreamAggregatorState aggregatorState) {
        for (short partition = 0; partition < aggregatorState.size(); partition++) {
            dump(aggregatorState, partition);
        }
    }

It's a map inside the aggregatorState, not an list;
Should be something like:

```
for (BucketStreamState state: aggregatorState) {
        dump(aggregatorState, state.partition());
    }
```

**Comment by WillGardella** [comment]
Hi Stanley - This issue is tracked as [KAFKAC-11](https://issues.couchbase.com/browse/KAFKAC-11).  Please use Jira for follow up on this item.

**Comment by waynesiu** [comment]
As suggested, please use Jira for further questions/comments.
