### ISSUE TITLE
Start streaming from known state

### ISSUE THREAD

**Issue by patelliandrea** [couchbase/couchbase-kafka-connector#6]
Hi,
I wrote a StateSerializer to save locally the offsets for each partition, but when the load function is called and the startSequenceNumber is different than 0, I am getting the following warning:

``` raw
WARN Unexpected status of StreamRequestResponse: ERR_RANGE (0x22, The requested value is outside the legal range) (com.couchbase.client.core.endpoint.dcp.DCPHandler:161)
```

and the application is not streaming any document.

Is it a bug or I'm just getting how it works wrong?

**Comment by patelliandrea** [comment]
Using the github version of the couchbase-jvm-core the ERR_RANGE problem disappeared.
The problem now is that whatever value I assign to the startSequenceNumber, it continues streaming all documents from the beginning, as if the startSequenceNumber is set to 0.

**Comment by patelliandrea** [comment]
Let's say I initialize the state as

``` java
BucketStreamState(1, 1, 4, 0xffffffff, 4, 0xffffffff);
```

The babysitter.log it's saying that it's impossible to create the stream because a rollback is required

``` raw
WARNING (beer-sample) DCP (Producer) eq_dcpq:CouchbaseKafka(1052163107) - (vb 1) Stream request failed because a rollback to seqno 0 is required (start seqno 4, vb_uuid 1, snapStartSeqno 4, snapEndSeqno 18446744073709551615)
memcached<0.79.0>: 2015-12-01T16:06:13.814513+01:00 WARNING (beer-sample) DCP (Producer) eq_dcpq:CouchbaseKafka(1052163107) - (vb 1) stream created with start seqno 0 and end seqno 18446744073709551615
```

**Comment by tk6022** [comment]
I am seeing bizarre behaviour relating to this too. I am using the built in ZookeeperStateSerializer (although intend to build a Consul based one at some point), and appear to only receive DCP events from documents created whilst the connector is running or between connector restarts. I do not receive DCP events for any documents created before a connector restart, and i too am seeing an error:

WARN  DCPHandler - Unexpected status of StreamRequestResponse: ERR_RANGE (0x22, The requested value is outside the legal range)

...which may or may not be related to the issue I'm seeing, or indeed the issue @patelliandrea is seeing. Any ideas?

**Comment by patelliandrea** [comment]
What I'm basically doing is rewriting this "connector' in order to build a proper kafka connector.
Instead of saving the sequence numbers on zookeeper, I'm using the `context.offsetStorageReader()` provided by kafka connect, so the committing of the offset is managed by kafka connect.

The problem comes out when I try to restart the streaming from a known state. Everytime I create a `BucketStreamAggregatorState` with `BucketStreamState` containing a start sequence number not equal to zero, the DCP stream is rollbacking and streaming all the document in the bucket.

Initially I thought I was doing something wrong, so I just started again from a clean situation recloning this project and trying to run it using the `ZookeeperStateSerializer` in `LOAD_AND_RESUME` mode.
The first run of the connector works flawlessly, but if I stop the connector and rerun it, when I initialize the states as something like

``` java
BucketStreamState(1, 1, 4, 0xffffffff, 4, 0xffffffff);
```

the stream is rollbacking giving me the error I listed in the issue above

```
WARNING (beer-sample) DCP (Producer) eq_dcpq:CouchbaseKafka(1052163107) - (vb 1) Stream request failed because a rollback to seqno 0 is required (start seqno 4, vb_uuid 1, snapStartSeqno 4, snapEndSeqno 18446744073709551615)
memcached<0.79.0>: 2015-12-01T16:06:13.814513+01:00 WARNING (beer-sample) DCP (Producer) eq_dcpq:CouchbaseKafka(1052163107) - (vb 1) stream created with start seqno 0 and end seqno 18446744073709551615
```

Right now I'm just reading all the streaming and discarding the messages I've already sent to Kafka, it would be nicer doing like you suggest on the readme 
"It is also possible to start with some known state or watching reduced set of partitions."

**Comment by avsej** [comment]
The issue with rollbacks and initialization has been fixed as a part of this change http://review.couchbase.org/57342

**Comment by tk6022** [comment]
@avsej Excellent thanks, when is this expected to be available in a release please?

**Comment by android-programmer** [comment]
@avsej Excellent thanks, when is this expected to be available in a release please?

**Comment by android-programmer** [comment]
I had this exact problem as well

**Comment by patelliandrea** [comment]
Thank you, now everything it's working.
I suggest to check the dependencies of the project. In the `couchbase-jvm-core` imported using gradle, the constructor `BucketStreamAggregatorState()` is not present as well as the method `BucketStreamAggregator.getCurrentState()`.

**Comment by tk6022** [comment]
Hi - Can you tell me when the fix for this will be in a release please? Surprised to hear @patelliandrea say "Thank you, now everything it's working." - unless you applied this patch yourself locally?

**Comment by ingenthr** [comment]
@tk6022 you can pull from the review link above, it's just a branch

**Comment by tk6022** [comment]
Thanks @ingenthr, but I would like to avoid maintaining my own version of the connector - do you know when this changeset will be included in a formal release of the kafka connector?

**Comment by avsej** [comment]
@tk6022 check the maven, it should be there already 1.2.1
